name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # Passo para instalar dependências Python para o Lambda
      - name: Install Python dependencies for process
        run: |
          if [ -f ./src/process/requirements.txt ]; then
            python3 -m venv venv
            source venv/bin/activate
            pip install -r ./src/process/requirements.txt
          fi

      # Passo para empacotar a Lambda de registro em um arquivo ZIP
      - name: Create ZIP file for process Lambda
        run: |
          mkdir -p lambda/process
          cp -r ./src/process/* lambda/process/
          cd lambda/process
          zip -r process_lambda_function.zip .
          cd ../../

      # Verificar se os arquivos ZIP foram criados
      - name: Check if ZIP files exist
        run: |
          if [ ! -f lambda/process/process_lambda_function.zip ]; then
            echo "Process Lambda ZIP file not found!"
            exit 1
          fi

      # Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Terraform Refresh
      - name: Terraform Refresh
        run: terraform refresh -input=false
        working-directory: ./infra

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra